name: json2dart_serialization
description: 一个网页版本的json转dart库
# version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

#dependencies:
#  path: ^1.4.1
dependencies:
  # Your other regular dependencies here
  json_annotation: ^4.9.0
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  json_serializable: ^6.8.0